version: '3'
services:
  db:
    image: postgres
    container_name: 1j1s-front-lighthouse-report
    restart: always
    environment:
      POSTGRES_DB: 1j1s-front-lighthouse-report
      POSTGRES_USER: admin-1j1s-front-lighthouse-report
      POSTGRES_PASSWORD: 1front1lighthouse
    ports:
      - 6543:5432
  lhserver:
    image: patrickhulce/lhci-server
    ports:
      - '9001:9001'
    volumes:
      - lhci-data:/data
volumes:
  lhci-data:
