name: Mise en veille Scalingo

on:
  schedule:
    # Du lundi au vendredi à 20h UTC => mise en veille des containers
    - cron: '0 19 * * 1-5'
  workflow_dispatch:

jobs:
  pause-recette:
    uses: ./.github/workflows/eco-scalingo.yml
    with:
      scalingo_app_name: 1j1s-front-lighthouse-report
      scalingo_region: osc-fr1
      number_of_container: 0
      statuscake_uptime_check_id: 6898859
    secrets:
      scalingo_api_token: ${{ secrets.SCALINGO_API_TOKEN }}
      statuscake_api_token: ${{ secrets.STATUSCAKE_API_TOKEN }}
