name: Déploiement Terraform

on:
  push:
    branches: [ main ]

jobs:

  # Déploiement sur Scalingo à chaque push sur la branche "main"
  recette:
    # uses: DNUM-SocialGouv/1j1s-front-lighthouse-report/.github/workflows/terraform.yml@main
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      apply: true
      environnement_name: scalingo
      environnement_url: https://1j1s-front-lighthouse-report.osc-fr1.scalingo.io/app/projects/1j1s-front-lighthouse-report/dashboard
